### ISSUE TITLE
AddCmd geht nicht

### ISSUE THREAD

**Issue by TheZyppi** [schroffl/Alfred#1]
Habe exakt alles so aufgebaut wie im Beispiel auch die daten habe ich richtig überhommen aber keine chance der macht nichts wenn ich .test mache

**Comment by schroffl** [comment]
Das liegt daran, dass ich ein paar größere Änderungen gemacht hab', das Beispiel aber nie geupdatet habe. Das Ganze sieht jetzt so aus, dass du bei addCmd eine Instanz von der Klasse User übergeben wird: 
```
bot.addCmd('test', function(User) {
    User.respond('Sir, how may I be of help');
}, false, '.test', 'This is a test command');
```

eine Alternative dazu wäre auch, das ist allerdings umständlicher:
```
bot.addCmd('test', function(User) {
    bot.sendMessage('Sir, how may I be of help', User.info.clid);
}, false, '.test', 'This is a test command');
```

**Comment by schroffl** [comment]
Ich werde mich demnächst auch mal daran machen ein kleines Wiki zu erstellen

**Comment by TheZyppi** [comment]
Es sollte eine Lösung geben alle Channels zu überwachen ein Algorithmus habe ich schon dafür und auch schon gesehen wenn du Hilfe brauchst ich helfe gerne.

**Comment by schroffl** [comment]
Gibt's denn irgendeine Möglichkeit außerhalb von Github Kontakt mit dir aufzunehmen? ^^

**Comment by TheZyppi** [comment]
Ich kann dir keine private nachricht senden deswegen komm einfach auf den Teamspeak Chameleon-gaming.de bin zwischen 8-17 Uhr und 19 - 0 Online heute einfach vorbeiu schauen und einen Serveradmin ansprechen auf Nico
