### ISSUE TITLE
CLIENTLIST ausgabe stimmt nicht

### ISSUE THREAD

**Issue by TheZyppi** [schroffl/Alfred#2]
Wenn due dir die Userliste ausgibst kommt nur ein Eintrag wenn du eine Callback function machst (Weiß nicht ob du das schon gemacht hast)

**Comment by schroffl** [comment]
Bei mir funktioniert die Liste.
```
var botfile = require('alfred-teamspeak');
var bot = new botfile.Alfred();

bot.configure({
	'login-pass': 'rvsmLSb6'
});

bot.on('login', function() {
	bot.clientlist(function(list) {
		console.log(list);
	});
});

bot.start();
```

![Konsolenausgabe](http://prntscr.com/89tw43)

**Comment by TheZyppi** [comment]
Ich hatte den command befehl benutzt 

bot.sendCommand('clientlist', {},function(err,resp){
        console.log(err)
        console.log(resp)
});

root@XXX: node server.js 
[14:50:49][*] Connected to 127.0.0.1:10011 as XXX
0
{ clid: '11',
  cid: '475',
  client_database_id: '1',
  client_nickname: 'XXX',
  client_type: '1' }

**Comment by schroffl** [comment]
Wenn du die komplette Antwort des TS sehen willst kannst du das hier machen:
```
bot.sendCommand('clientlist', function(err, resp, raw) {
    console.log(raw);
});
```
Die Antwort ist ein einziger String, heißt also dass der Wert .clid überschrieben wird wenn er ein weiteres Mal vorkommt. bot.clientlist() nimmt die raw response und konvertiert das Ganze dann in ein Array
