### ISSUE TITLE
Bot sendet an jeden Server

### ISSUE THREAD

**Issue by TheZyppi** [schroffl/Alfred#3]
Hey ich hab noch ein Fehler gefunden:

wenn ich

bot.say(STRING)

mache wird der Text an ALLEN virtuellen Servern gesendet

Benutze statt 

gm msg={msg}

sendtextmessage targetmode=1 target={serverID} msg={text}

und mache eine eigene funktion dafür

**Comment by schroffl** [comment]
Okay, danke für den Tipp :)

**Comment by schroffl** [comment]
Du kannst bei bot.configure() den Wert 'virtual-server' konfigurieren (Standard: 1). Die Funktion sendet jetzt eine Nachricht an den dort angegebenen Server
